flake: Switch to nixpkgs 26.05
I'm getting these:

error: builder for '/nix/store/xmwc3j5dd73wh7bqzwqvpzsxmfwhk2i5-vm-test-run-run-benchprog-integration.drv' failed with exit code 1;
       last 25 log lines:
       >     self.test_script()
       >     ~~~~~~~~~~~~~~~~^^
       >   File "/nix/store/s837rah6wid0dwz7s3fx1hk8vzb2i48v-nixos-test-driver-1.1/lib/python3.13/site-packages/test_driver/driver.py", line 204, in test_script
       >     exec(self.tests, symbols, None)
       >     ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "<string>", line 1, in <module>
       >   File "/nix/store/s837rah6wid0dwz7s3fx1hk8vzb2i48v-nixos-test-driver-1.1/lib/python3.13/site-packages/test_driver/driver.py", line 256, in start_all
       >     machine.start()
       >     ~~~~~~~~~~~~~^^
       >   File "/nix/store/s837rah6wid0dwz7s3fx1hk8vzb2i48v-nixos-test-driver-1.1/lib/python3.13/site-packages/test_driver/machine/__init__.py", line 1094, in start
       >     self.qmp_client = QMPSession.from_path(self.qmp_path)
       >                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
       >   File "/nix/store/s837rah6wid0dwz7s3fx1hk8vzb2i48v-nixos-test-driver-1.1/lib/python3.13/site-packages/test_driver/machine/qmp.py", line 50, in from_path
       >     return cls(sock)
       >   File "/nix/store/s837rah6wid0dwz7s3fx1hk8vzb2i48v-nixos-test-driver-1.1/lib/python3.13/site-packages/test_driver/machine/qmp.py", line 39, in __init__
       >     hello = self._wait_for_new_result()
       >   File "/nix/store/s837rah6wid0dwz7s3fx1hk8vzb2i48v-nixos-test-driver-1.1/lib/python3.13/site-packages/test_driver/machine/qmp.py", line 58, in _wait_for_new_result
       >     self.read_pending_messages()
       >     ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
       >   File "/nix/store/s837rah6wid0dwz7s3fx1hk8vzb2i48v-nixos-test-driver-1.1/lib/python3.13/site-packages/test_driver/machine/qmp.py", line 62, in read_pending_messages
       >     line = self.reader.readline()
       >   File "/nix/store/3lll9y925zz9393sa59h653xik66srjb-python3-3.13.9/lib/python3.13/socket.py", line 719, in readinto
       >     return self._sock.recv_into(b)
       >            ~~~~~~~~~~~~~~~~~~~~^^^
       > ConnectionResetError: [Errno 104] Connection reset by peer
       For full logs, run:
         nix-store -l /nix/store/xmwc3j5dd73wh7bqzwqvpzsxmfwhk2i5-vm-test-run-run-benchprog-integration.drv

Maybe fixed in new version?